# Northern Sami translations for InAcademia.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the InAcademia project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
msgid ""
msgstr ""
"Project-Id-Version: InAcademia 0.1.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-10 16:04+0100\n"
"PO-Revision-Date: 2015-03-10 16:14+0100\n"
"Last-Translator: Rebecka Gulliksson <rebecka.gulliksson@umu.se>\n"
"Language-Team: InAcademia <tech@inacademia.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Language: sv\n"
"X-Generator: Poedit 1.7.4\n"

#: src/svs/inacademia_server.py:195 src/svs/inacademia_server.py:212
#: src/svs/inacademia_server.py:248 src/svs/inacademia_server.py:261
#: src/svs/inacademia_server.py:274
msgid "Page not found."
msgstr "Sidan kunde inte hittas."

#: src/svs/inacademia_server.py:345
msgid "Domain"
msgstr "Domän"

#: src/svs/inacademia_server.py:350
msgid "Country"
msgstr "Land"

#: src/svs/inacademia_server.py:374
msgid "Affiliation"
msgstr "Anknytning"

#: src/svs/inacademia_server.py:374
msgid "Identifier"
msgstr "Identifierare"

#: src/svs/inacademia_server.py:374
msgid "Authentication time"
msgstr "Tid för autentisering"

#: src/svs/inacademia_server.py:411 src/svs/oidc.py:92
msgid ""
"We could not complete your validation because an error occurred while "
"handling your request. Please return to the service which initiated the "
"validation request and try again."
msgstr ""
"Vi kunde inte slutföra din validering eftersom ett fel inträffade medan "
"vi hanterade din förfrågan. Var vänlig återgå till tjänsten som "
"initierade valideringen och försök igen."

#: src/svs/oidc.py:154
msgid ""
"The authentication request could not be processed. Please return to the "
"service which initiated the validation request and try again."
msgstr ""
"Autentiseringsförfrågan kunde inte hanteras. Var vänlig återgå till "
"tjänsten som initierade valideringen och försök igen."

#: src/svs/oidc.py:161
msgid "Configuration error for the service."
msgstr "Konfigurationsfel för tjänsten."

#: src/svs/user_interaction.py:48
msgid ""
"<strong>'{client_name}'</strong> requires the information below to be "
"transferred:"
msgstr ""
"<strong>'{client_name}'</strong> kräver att nedanstående information "
"överförs:"

#: src/svs/templates/consent.mako:38
msgid "Consent - Your consent is required to continue."
msgstr "Medgivande - Ditt medgivande krävs för att fortsätta."

#: src/svs/templates/consent.mako:61
msgid "Ok, accept"
msgstr "Ok, acceptera"

#: src/svs/templates/consent.mako:66
msgid "No, cancel"
msgstr "Nej, avbryt"

#: src/svs/templates/consent.mako:81 src/svs/templates/error.mako:68
msgid "Terms of service"
msgstr "Villkor för tjänsten"

#: src/svs/templates/error.mako:26
msgid "Error - An error occurred."
msgstr "Fel - Ett fel inträffade."

#: src/svs/templates/error.mako:53
msgid "Timestamp"
msgstr "Tidstämpel"

#: src/svs/templates/error.mako:58
msgid "Error id"
msgstr "Fel id"
